version: '3.8'

services:
  kedro:
    build: .
    container_name: kedro_australia_climate
    volumes:
      - .:/home/kedro
    ports:
      - "8888:8888"  # JupyterLab
      - "4141:4141"  # Kedro Viz
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  postgres:
    image: postgres:14
    container_name: postgres_aus_climate
    environment:
      POSTGRES_USER: kedro_user
      POSTGRES_PASSWORD: kedro_pass
      POSTGRES_DB: climate_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: