version: '3'
services:
  kedro:
    build: .
    container_name: kedro_australia_climate
    volumes:
      - .:/home/kedro  # Monta el directorio actual en el contenedor
    ports:
      - "8888:8888"   # Expone Jupyter en localhost:8888
    tty: true
