# ─────────────────────────────────────────────
# Parámetros para el Modelo de Regresión
# ─────────────────────────────────────────────
regression_model_params:
  model_type: "RandomForestRegressor" # Podrías cambiar a otro modelo fácilmente
  n_estimators: 100
  max_depth: 10
  random_state: 42
  n_jobs: -1 # Usa todos los cores disponibles

# Parámetros para split del modelo de regresión
test_size: 0.2 # 20% para test
random_state: 42 # Para reproducibilidad

