# ─────────────────────────────────────────────
# Parámetros para el Modelo de Regresión
# ─────────────────────────────────────────────
regression_model_params:
  model_type: "RandomForestRegressor" # Podrías cambiar a otro modelo fácilmente
  n_estimators: 100
  max_depth: 10
  random_state: 42
  n_jobs: -1 # Usa todos los cores disponibles

# Parámetros para split del modelo de regresión
test_size: 0.2 # 20% para test
random_state: 42 # Para reproducibilidad

# Identificador único para esta ejecución
run_id: "run_001" # Identificador de ejecución para tracking

# Parámetros específicos para el modelo de Naive Bayes
prediction_date: null  # Si es null, se usará la fecha más reciente en los datos

num_days: 10
start_date: "2025-06-25"

# ─────────────────────────────────────────────
# Parámetros para Modelos No Supervisados
# ─────────────────────────────────────────────

# K-means clustering
kmeans_params:
  n_clusters: 4
  random_state: 42 # Número de inicializaciones con diferentes centroides

# DBSCAN clustering
dbscan_params:
  eps: 0.5
  min_samples: 5  # Número mínimo de muestras en un vecindario para que un punto sea considerado core point

# PCA dimensionality reduction
pca_params:
  n_components: 3  # Número de componentes principales a mantener

# Isolation Forest para detección de anomalías
isolation_forest_params:
  contamination: 0.05  # Proporción de anomalías esperadas en los datos (5%)

# ─────────────────────────────────────────────
# Parámetros para Interpretación y Propuestas
# ─────────────────────────────────────────────

# Directorio para los reportes y visualizaciones
interpretation_output_dir: "data/08_reporting/interpretations"